name: Event Filters
on:
  push:
    branches:
      - dev
      - release/*
    paths-ignore:
      - 'docs/**'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print event type
        run: echo "I've been triggered by ${{ github.event_name }} event"
